plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.148'
}

group = 'com.ttp'
version = '1.0.1'
base.archivesName = 'ttp-neoforge-1.21.1'
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.235'
    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
    }
    mods {
        ttp { sourceSet sourceSets.main }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest.attributes('Implementation-Version': project.version)
}
